# Generated by Django 2.1.1 on 2018-11-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gandhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gn_matter', models.TextField(blank=True, null=True)),
                ('gn_image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Polytechnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_matter', models.TextField(blank=True, null=True)),
                ('pt_image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Prakasam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_matter', models.TextField(blank=True, null=True)),
                ('pk_image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Updatedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_name', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(default=None)),
                ('update_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='prakasam',
            name='pk_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praksam_data', to='updates.Updatedata'),
        ),
        migrations.AddField(
            model_name='polytechnic',
            name='pt_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polytechnic_data', to='updates.Updatedata'),
        ),
        migrations.AddField(
            model_name='gandhi',
            name='gn_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gandhi_data', to='updates.Updatedata'),
        ),
    ]
