# Generated by Django 2.1.1 on 2018-11-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gandhi',
            old_name='gn_image',
            new_name='gandhi_image',
        ),
        migrations.RenameField(
            model_name='gandhi',
            old_name='gn_matter',
            new_name='gandhi_matter',
        ),
        migrations.RenameField(
            model_name='gandhi',
            old_name='gn_view',
            new_name='gandhi_view',
        ),
        migrations.RenameField(
            model_name='polytechnic',
            old_name='pt_image',
            new_name='polytechnic_image',
        ),
        migrations.RenameField(
            model_name='polytechnic',
            old_name='pt_matter',
            new_name='polytechnic_matter',
        ),
        migrations.RenameField(
            model_name='polytechnic',
            old_name='pt_view',
            new_name='polytechnic_view',
        ),
        migrations.RenameField(
            model_name='prakasam',
            old_name='pk_image',
            new_name='prakasam_image',
        ),
        migrations.RenameField(
            model_name='prakasam',
            old_name='pk_matter',
            new_name='prakasam_matter',
        ),
        migrations.RemoveField(
            model_name='prakasam',
            name='pk_view',
        ),
        migrations.AddField(
            model_name='gandhi',
            name='gandhi_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='polytechnic',
            name='polytechnic_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='prakasam',
            name='prakasam_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='prakasam',
            name='prakasam_view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prakasam_data', to='updates.Updatedata'),
        ),
    ]
